type ClientRoot = { render(node: unknown): void; unmount(): void };
type ClientDom = { createRoot?: (container: Element) => ClientRoot; hydrateRoot?: (container: Element, node: unknown) => ClientRoot };
const reactDom = Function("return globalThis.__dshArchiveReactDOM")() as typeof import("react-dom");
const reactDomClient = Function("return globalThis.__dshArchiveReactDOMClient")() as ClientDom | undefined;
export const createPortal = reactDom.createPortal;
export const flushSync = reactDom.flushSync;
export const createRoot = reactDomClient?.createRoot;
export const hydrateRoot = reactDomClient?.hydrateRoot;
export const findDOMNode = reactDom.findDOMNode;
export const unmountComponentAtNode = reactDom.unmountComponentAtNode;
export const unstable_batchedUpdates = reactDom.unstable_batchedUpdates;
export const version = reactDom.version;
export default reactDom;
