type DomExtras = { createRoot?: (container: Element) => unknown; hydrateRoot?: (container: Element, node: unknown) => unknown };
const reactDom = Function("return globalThis.__dshArchiveReactDOM")() as typeof import("react-dom") & DomExtras;
export const createPortal = reactDom.createPortal;
export const flushSync = reactDom.flushSync;
export const createRoot = reactDom.createRoot;
export const hydrateRoot = reactDom.hydrateRoot;
export const findDOMNode = reactDom.findDOMNode;
export const unmountComponentAtNode = reactDom.unmountComponentAtNode;
export const unstable_batchedUpdates = reactDom.unstable_batchedUpdates;
export const version = reactDom.version;
export default reactDom;
